In [2]:
import openpyxl as xl
import pandas as pd

In [6]:
exl = xl.load_workbook('qa-sept23.xlsx')
df = exl.active

In [7]:
for row in range(0, df.max_row):
    for col in df.iter_cols(1, df.max_column):
        print(col[row].value)

None
   AURO TEXTILE-II
None
None
None
None
None
None
None
None
None
         DAILY QA PRODUCTION REPORT
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
DATE
=Data!A1
None
None
None
None
None
None
None
None
PRODUCTION
FTD
MTD
PRO-TARGET
PACKING % (FTD)
PACKING % MTD)
LAST MONTH PKG %AGE
None
None
None
TOTAL PRODUCTION
=Summary!I7
=Summary!J7
40.00 Lac
=AVERAGE(F7,F8)
=AVERAGE(G7,G8)
=AVERAGE(H7,H8)
None
None
None
YARN DYED
=Summary!G7
=Summary!H7
22.00 Lac
=+Summary!H30%
=+Summary!I30%
0.9721
None
None
None
PRINT
=Summary!C7
=Summary!D7
18.00 Lac
=+Summary!H25%
=+Summary!I25%
0.9481
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None

In [5]:
df_new = pd.read_excel('qa-sept23.xlsx', sheet_name='Data', skiprows=[0])
df_new

,DATE,Print,Print Yd,Print PD Yardage,Print Yd Yardage,Piece Dyed,RG/RS,PRINT Q6,Print FRC,PRINT TOTAL,Yarn Dyed,Yarn Dyed Yardage,RG/RS.1,YD Q6,Yarn Dyed FRC,YD TOTAL,WIP PRINT,WIP YARN DYED,WIP TOTAL,Last Bale Number
0,2023-09-01 00:00:00,13132.5,0.0,136.00,0.0,55.0,175.0,143.0,201.00,NaN,39234.0,268.00,0.0,227.0,848.00,NaN,13000.0,42000.0,NaN,3.750021e+11
1,2023-09-02 00:00:00,16410.1,1258.0,333.00,0.0,0.0,7.0,115.0,564.00,NaN,76963.0,339.87,0.0,129.0,824.00,NaN,28900.0,27050.0,NaN,3.750021e+11
2,2023-09-03 00:00:00,66328.0,128.0,0.00,0.0,0.0,327.0,30.0,739.00,NaN,73566.5,0.00,0.0,98.0,837.00,NaN,20000.0,34400.0,NaN,3.750021e+11
3,2023-09-04 00:00:00,36518.7,0.0,215.00,0.0,128.0,0.0,100.0,483.00,NaN,72512.0,326.00,0.0,107.0,715.00,NaN,11700.0,27700.0,NaN,3.750021e+11
4,2023-09-05 00:00:00,20743.0,26.0,359.10,0.0,3527.0,2146.0,124.0,433.00,NaN,75653.1,109.00,25.0,55.0,966.00,NaN,16350.0,35350.0,NaN,3.750021e+11
5,2023-09-06 00:00:00,38733.7,0.0,374.00,0.0,0.0,0.0,111.0,619.00,NaN,66950.5,221.00,0.0,135.0,865.00,NaN,14400.0,34600.0,NaN,3.750021e+11
6,2023-09-07 00:00:00,32033.0,0.0,162.00,0.0,0.0,0.0,123.0,800.00,NaN,62522.0,261.01,0.0,92.0,584.00,NaN,29410.0,23520.0,NaN,3.750021e+11
7,2023-09-08 00:00:00,32631.3,1141.0,423.04,0.0,658.0,10.0,182.0,295.00,NaN,67322.0,171.04,0.0,28.0,957.00,NaN,26000.0,27200.0,NaN,3.750021e+11
8,2023-09-09 00:00:00,47167.7,0.0,234.00,0.0,0.0,145.0,189.0,755.00,NaN,88236.6,396.10,0.0,81.0,929.00,NaN,20130.0,28400.0,NaN,3.750021e+11
9,2023-09-10 00:00:00,36377.7,0.0,0.00,0.0,28.0,33.0,157.0,995.00,NaN,47359.5,0.00,0.0,64.0,537.00,NaN,31500.0,21300.0,NaN,3.750021e+11
10,2023-09-11 00:00:00,71644.0,0.0,304.00,38.0,2581.0,17.0,635.0,1001.00,NaN,38414.0,525.08,0.0,104.0,522.00,NaN,27400.0,33000.0,NaN,3.750021e+11
11,2023-09-12 00:00:00,37525.0,38.0,471.04,0.0,395.0,117.0,173.0,346.00,NaN,90255.0,414.00,0.0,89.0,972.00,NaN,19000.0,37410.0,NaN,3.750021e+11
12,2023-09-13 00:00:00,62751.2,0.0,304.04,0.0,643.0,0.0,252.0,773.88,NaN,55743.0,105.10,57.0,97.0,662.42,NaN,16400.0,37800.0,NaN,3.750021e+11
13,2023-09-14 00:00:00,41048.0,2577.0,140.02,0.0,299.0,18.0,105.0,694.00,NaN,78346.0,136.00,37.0,103.0,744.00,NaN,27410.0,12700.0,NaN,3.750021e+11
14,2023-09-15 00:00:00,60004.0,3769.0,78.00,0.0,41.0,138.0,172.0,486.00,NaN,50745.5,228.00,0.0,146.0,974.00,NaN,14520.0,40260.0,NaN,3.750021e+11
15,2023-09-16 00:00:00,34662.0,6205.0,75.00,0.0,485.0,0.0,110.0,593.00,NaN,95583.8,108.00,0.0,95.0,864.00,NaN,29245.0,34120.0,NaN,3.750021e+11
16,2023-09-17 00:00:00,58621.9,216.0,0.00,0.0,0.0,0.0,NaN,936.00,NaN,80802.7,0.00,0.0,7.0,811.00,NaN,30889.0,30650.0,NaN,3.750021e+11
17,2023-09-18 00:00:00,87668.7,812.0,310.00,25.0,0.0,0.0,241.0,1123.00,NaN,47485.6,528.70,0.0,133.0,527.00,NaN,40530.0,24130.0,NaN,3.750021e+11
18,2023-09-19 00:00:00,35959.7,12.0,94.51,0.0,0.0,0.0,36.0,231.00,NaN,75625.0,329.20,2294.0,106.0,1147.00,NaN,25310.0,38410.0,NaN,3.750021e+11
19,2023-09-20 00:00:00,22599.7,2708.0,492.14,0.0,2906.0,0.0,337.0,428.00,NaN,124795.5,307.85,164.0,37.0,1258.00,NaN,24296.0,40521.0,NaN,3.750021e+11
20,2023-09-21 00:00:00,50264.0,417.0,304.00,0.0,0.0,0.0,185.0,726.00,NaN,93518.2,603.02,0.0,64.0,724.00,NaN,28315.0,39562.0,NaN,3.750021e+11
21,2023-09-22 00:00:00,84706.2,762.0,211.00,0.0,0.0,0.0,107.0,810.00,NaN,96775.3,221.02,0.0,85.0,1175.00,NaN,14510.0,48720.0,NaN,3.750021e+11
22,2023-09-23 00:00:00,48759.1,463.0,241.02,0.0,0.0,0.0,169.0,627.00,NaN,124222.6,153.04,0.0,102.0,727.00,NaN,25316.0,34481.0,NaN,3.750021e+11
23,2023-09-24 00:00:00,74032.5,106.0,0.00,0.0,0.0,0.0,NaN,627.00,NaN,81134.6,0.00,421.0,38.0,862.00,NaN,16800.0,36200.0,NaN,3.750021e+11
24,2023-09-25 00:00:00,37470.0,2238.0,409.02,0.0,0.0,669.0,103.0,960.00,NaN,92935.8,641.00,0.0,291.0,717.00,NaN,21230.0,28410.0,NaN,3.750021e+11
25,2023-09-26 00:00:00,77621.3,0.0,211.02,0.0,0.0,587.0,124.0,1194.00,NaN,71196.6,122.52,43.0,55.0,779.00,NaN,22410.0,28487.0,NaN,3.750021e+11
26,2023-09-27 00:00:00,78320.7,15756.0,382.00,0.0,0.0,0.0,194.0,1515.00,NaN,50633.0,315.00,0.0,NaN,1060.00,NaN,37401.0,21800.0,NaN,3.750021e+11
27,2023-09-28 00:00:00,98405.6,161.0,159.00,0.0,0.0,0.0,154.0,1253.00,NaN,85876.1,323.40,0.0,172.0,1318.00,NaN,25125.0,35400.0,NaN,3.750021e+11
28,2023-09-29 00:00:00,53368.4,1512.0,284.10,0.0,0.0,0.0,194.0,1297.00,NaN,94787.6,137.00,2860.0,37.0,948.00,NaN,42510.0,24850.0,NaN,3.750021e+11
29,2023-09-30 00:00:00,153893.0,98.0,279.00,0.0,0.0,58.0,NaN,1057.00,NaN,35049.5,300.50,397.0,82.0,951.00,NaN,8210.0,18410.0,NaN,3.750021e+11
30,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN